[package]
name = "FakeCrypt"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.30"
whoami = "1.4"
hostname = "0.3"
aes = "0.8"
cbc = "0.1"
cipher = "0.4"
rand = "0.8"
dirs = "5.0"

[profile.release]
strip = "symbols"
